### 허브 배송 관리자 생성
POST localhost:19091/api/delivery-staff/hub
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiSFVCX01BTkFHRVIiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3MzQyMDkyMDYsImV4cCI6MTczNDIxMjgwNn0.VahAVn4tiwvb1eC0zSXo9Dw_Xz3GwFo4VNn26iQCmo7ZmIehIVO1904Xz2c5e4-iynQ66y_EP9qV6ztLzwgzaQ

{
  "deliveryStaffId": 1
}

### 업체 배송 관리자 생성
POST localhost:19094/api/delivery-staff/company
Content-Type: application/json
## Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6Ik1BU1RFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczNDAwMDM2MywiZXhwIjoxNzM0MDAzOTYzfQ.Q_5qCW1UfbVneUrNBN3zsBTfXuxTVGMFj1dKfd6qu7zLNmNhmTgL99cgFa5OhX72kcNnn1XIxxSJm6eIvXYhKQ

{
"deliveryStaffId": 2,
"hubId": "42af8b30-3d6a-43ae-861b-c76eb25c967f"
}

### 배송 관리자 목록 조회
GET localhost:19094/api/delivery-staff?size=30&deliveryOrder=0&staffType=HUB_STAFF
Content-Type: application/json

### 배송 관리자 상세 조회
GET localhost:19094/api/delivery-staff/2
Content-Type: application/json

### 배송 관리자 수정 (허브->업체)
PATCH localhost:19094/api/delivery-staff/1
Content-Type: application/json

{
  "staffType": "COMPANY_STAFF",
  "hubId": "42af8b30-3d6a-43ae-861b-c76eb25c967f"
}

### 배송 관리자 수정 (업체->허브)
PATCH localhost:19094/api/delivery-staff/1
Content-Type: application/json

{
  "staffType": "HUB_STAFF"
}

### 배송 관리자 수정 (업체 hubId 변경)
PATCH localhost:19094/api/delivery-staff/2
Content-Type: application/json

{
  "staffType": "COMPANY_STAFF",
  "hubId": "52af8b30-3d6a-43ae-861b-c76eb25c967f"
}

### 배송 관리자 삭제
DELETE localhost:19094/api/delivery-staff/2
Content-Type: application/json
